# Generated by Django 5.2.3 on 2025-06-22 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorModel',
            fields=[
                ('vendedorId', models.AutoField(primary_key=True, serialize=False)),
                ('nombreVendedor', models.CharField(max_length=100, verbose_name='Nombre del Vendedor')),
                ('apellidoVendedor', models.CharField(max_length=100, verbose_name='Apellido del Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='VentasModel',
            fields=[
                ('ventaId', models.AutoField(primary_key=True, serialize=False)),
                ('fechaVenta', models.DateField(verbose_name='Fecha de la Venta')),
                ('cantidadVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Vendida en Dolares')),
                ('vendedorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorventas.vendedormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReglasModel',
            fields=[
                ('reglaId', models.AutoField(primary_key=True, serialize=False)),
                ('metaVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Venta para Comision')),
                ('cantidadComision', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de Comision en Porcentaje')),
                ('vendedorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorventas.vendedormodel')),
                ('ventasId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorventas.ventasmodel')),
            ],
        ),
    ]
