# Generated by Django 5.2.3 on 2025-06-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglasmodel',
            name='vendedorId',
        ),
        migrations.RemoveField(
            model_name='reglasmodel',
            name='ventasId',
        ),
    ]
